apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: <namespace-name>
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP